# Generated by Django 3.2.23 on 2024-01-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('question', models.TextField()),
                ('correct', models.TextField()),
                ('incorrect_1', models.TextField()),
                ('incorrect_2', models.TextField()),
                ('incorrect_3', models.TextField()),
            ],
        ),
    ]
