# Generated by Django 3.2.23 on 2024-01-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='incorrect_1',
            field=models.TextField(default='\u3000'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='incorrect_2',
            field=models.TextField(default='\u3000'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='incorrect_3',
            field=models.TextField(default='\u3000'),
        ),
    ]
