# Generated by Django 3.2.23 on 2024-01-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0002_auto_20240102_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='incorrect_3',
            field=models.TextField(default='\u3000', null=True),
        ),
    ]
