# Generated by Django 3.2.23 on 2024-01-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0003_alter_questions_incorrect_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='incorrect_1',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='incorrect_2',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='incorrect_3',
            field=models.TextField(default='null'),
        ),
    ]
