# Generated by Django 3.2.23 on 2024-01-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0004_auto_20240102_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='discription',
            field=models.TextField(default='null'),
        ),
    ]
