# Generated by Django 3.2.23 on 2024-01-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0005_questions_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(default='00')),
            ],
        ),
    ]
