# Generated by Django 3.2.23 on 2024-01-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0006_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='question_id',
            field=models.IntegerField(default='0'),
        ),
    ]
