# Generated by Django 3.2.23 on 2024-01-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0007_alter_test_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question'),
        ),
        migrations.AddField(
            model_name='questions',
            name='incorrect_4',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='questions',
            name='incorrect_5',
            field=models.TextField(default='null'),
        ),
    ]
