# Generated by Django 3.2.23 on 2024-01-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0008_auto_20240102_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.IntegerField(default='0'),
        ),
    ]
