# Generated by Django 3.2.23 on 2024-01-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0009_alter_questions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correct',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
    ]
