# Generated by Django 3.2.23 on 2024-01-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0010_auto_20240103_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
