# Generated by Django 3.2.23 on 2024-01-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sweb', '0011_auto_20240103_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
